import { createHash, randomBytes } from "node:crypto";
import { lstatSync, readFileSync } from "node:fs";
import { link, lstat, open, unlink } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { generateGradientFfx } from "../../dist/ffx-gradient.js";
import { readLiveProofConfig, validateLiveProofConfig } from "./validate-config.mjs";

const REPOSITORY_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function templatePath(kind) {
  return join(REPOSITORY_ROOT, "fixtures", "native-gradient", `${kind}-template.ffx`);
}

export function buildLiveProofPreset(value) {
  const config = validateLiveProofConfig(value, { requireTarget: false });
  const path = templatePath(config.kind);
  const state = lstatSync(path);
  if (state.isSymbolicLink() || !state.isFile() || state.size > 8 * 1024 * 1024) {
    throw new Error("canonical live-proof template must be a bounded non-symlink regular file");
  }
  const template = readFileSync(path);
  const generated = generateGradientFfx(new Uint8Array(template), config.kind, config.gradient);
  const bytes = Buffer.from(generated.bytes);
  return {
    config,
    bytes,
    report: generated.report,
    templatePath: path,
    templateSha256: sha256(template),
    presetSha256: sha256(bytes),
  };
}

async function publishNoClobber(path, bytes) {
  try {
    await lstat(path);
    throw new Error(`preset already exists: ${path}`);
  } catch (error) {
    if (!(error && typeof error === "object" && error.code === "ENOENT")) throw error;
  }
  const temporary = `${path}.tmp-${process.pid}-${randomBytes(8).toString("hex")}`;
  let temporaryExists = false;
  try {
    const handle = await open(temporary, "wx", 0o600);
    temporaryExists = true;
    try {
      await handle.writeFile(bytes);
      await handle.sync();
    } finally {
      await handle.close();
    }
    try {
      await link(temporary, path);
    } catch (error) {
      if (error && typeof error === "object" && error.code === "EEXIST") {
        throw new Error(`preset already exists: ${path}`);
      }
      throw error;
    }
    await unlink(temporary);
    temporaryExists = false;
  } finally {
    if (temporaryExists) await unlink(temporary).catch(() => {});
  }
}

export async function prepareLiveProofPreset(value) {
  const built = buildLiveProofPreset(value);
  if (built.presetSha256 !== built.config.presetSha256) {
    throw new Error(`generated preset SHA-256 mismatch: expected ${built.config.presetSha256}, got ${built.presetSha256}`);
  }
  await publishNoClobber(built.config.presetPath, built.bytes);
  const readback = readFileSync(built.config.presetPath);
  const readbackHash = sha256(readback);
  if (readbackHash !== built.presetSha256 || !readback.equals(built.bytes)) {
    throw new Error("generated preset readback verification failed");
  }
  return {
    schemaVersion: 1,
    kind: built.config.kind,
    stopCount: built.config.stopCount,
    presetPath: built.config.presetPath,
    byteLength: built.bytes.byteLength,
    sha256: built.presetSha256,
    templatePath: built.templatePath,
    templateSha256: built.templateSha256,
    structuralReport: built.report,
  };
}

export async function ensureLiveProofPreset(value) {
  const built = buildLiveProofPreset(value);
  if (built.presetSha256 !== built.config.presetSha256) {
    throw new Error(`generated preset SHA-256 mismatch: expected ${built.config.presetSha256}, got ${built.presetSha256}`);
  }
  try {
    const state = await lstat(built.config.presetPath);
    if (state.isSymbolicLink() || !state.isFile()) {
      throw new Error("existing preset must be a non-symlink regular file");
    }
    const existing = readFileSync(built.config.presetPath);
    if (sha256(existing) !== built.presetSha256 || !existing.equals(built.bytes)) {
      throw new Error("existing preset does not exactly match deterministic generated bytes");
    }
    return {
      schemaVersion: 1,
      created: false,
      presetPath: built.config.presetPath,
      byteLength: built.bytes.byteLength,
      sha256: built.presetSha256,
      templatePath: built.templatePath,
      templateSha256: built.templateSha256,
      structuralReport: built.report,
    };
  } catch (error) {
    if (!(error && typeof error === "object" && error.code === "ENOENT")) throw error;
  }
  const report = await prepareLiveProofPreset(built.config);
  return { ...report, created: true };
}

function parseArguments(args) {
  if (args.length !== 3 || args[0] !== "--config" || !["--explain", "--write"].includes(args[2])) {
    throw new Error("usage: prepare-preset.mjs --config <absolute.json> (--explain | --write)");
  }
  return { configPath: args[1], mode: args[2] };
}

async function main() {
  const args = parseArguments(process.argv.slice(2));
  const config = await readLiveProofConfig(args.configPath, { requireTarget: false });
  if (args.mode === "--explain") {
    const built = buildLiveProofPreset(config);
    process.stdout.write(`${JSON.stringify({
      schemaVersion: 1,
      write: false,
      kind: config.kind,
      stopCount: config.stopCount,
      presetPath: config.presetPath,
      byteLength: built.bytes.byteLength,
      sha256: built.presetSha256,
      templatePath: built.templatePath,
      templateSha256: built.templateSha256,
      structuralReport: built.report,
    }, null, 2)}\n`);
    return;
  }
  const report = await prepareLiveProofPreset(config);
  process.stdout.write(`${JSON.stringify({ ...report, write: true }, null, 2)}\n`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
